version: "3"
services: 
    reverseproxy:
        image: kemsty2/reverseproxy:dev
        ports: 
            - 8080:8080
        restart: always
        depends_on: 
            - backend-user
            - backend-feed
    backend-user:
        image: kemsty2/udacity-restapi-user:dev
        restart: always
        environment: 
            POSTGRESS_USERNAME: $POSTGRESS_USERNAME
            POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
            POSTGRESS_DB: $POSTGRESS_DB 
            POSTGRESS_HOST: $POSTGRESS_HOST 
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_BUCKET: $AWS_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://157.245.172.36:8100"
    backend-feed: 
        image: kemsty2/udacity-restapi-feed:dev
        restart: always
        volumes:
            - $HOME/.aws:/root/.aws
        environment: 
            POSTGRESS_USERNAME: $POSTGRESS_USERNAME
            POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
            POSTGRESS_DB: $POSTGRESS_DB 
            POSTGRESS_HOST: $POSTGRESS_HOST 
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_BUCKET: $AWS_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://157.245.172.36:8100"
    frontend:
        image: kemsty2/frontend:dev
        ports:
            - "8100:80"