version: "3"
services: 
    reverseproxy:
        build:
            context: .
        image: kemsty2/reverseproxy:dev
    backend_user:
        build: 
            context: ../../udacity-restapi-user
        image: kemsty2/udacity-restapi-user:dev
    backend_feed:
        build: 
            context: ../../udacity-restapi-feed
        image: kemsty2/udacity-restapi-feed:dev
    frontend:
        build: 
            context: ../../udacity-frontend
        image: kemsty2/frontend:dev